version: "3.9"

services:
  web:
    build: .
    container_name: exerciser_web_test
    command: pytest
    env_file:
      - .env.test
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: exerciser_db_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_test:/var/lib/postgresql/data/

  redis:
    image: redis:latest
    container_name: exerciser_redis_test
    ports:
      - "6379:6379"

volumes:
  postgres_data_test:
