# Generated by Django 4.2.2 on 2023-07-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_task_active_task_created_at_task_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlackUserResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slack_user_id", models.CharField(max_length=32)),
                ("slack_user_username", models.CharField(max_length=32)),
                ("slack_user_name", models.CharField(max_length=64)),
                ("response", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.task"
                    ),
                ),
            ],
        ),
    ]
