# Generated by Django 4.2.2 on 2023-10-01 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_slackanswer_slackuserresponse_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slackanswer",
            name="text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="slackuserresponse",
            name="answer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.slackanswer",
            ),
        ),
    ]
