apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: exerciser-admin-ingres
  namespace: v-zadorozhnii-dev
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/whitelist-source-range: 52.31.241.51/32,163.172.126.46/32,77.122.224.16/32
spec:
  tls:
    - hosts:
        - exerciser.raccoongang.com
      secretName: exerciser-tls
  rules:
    - host: exerciser.raccoongang.com
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: django-service
                port:
                  number: 8000
